In [16]:
#importação das bibliotecas
import pandas as pd
import os

In [17]:
#função para limpar os dados de cada arquivo csv anual e salvar como novo arquivo

def limpar_dados_incendio(nome_arquivo, novo_arquivo):
    df = pd.read_csv(nome_arquivo)
    df = df.drop(columns=["id_bdq", "foco_id"])
    df[["data", "hora"]] = df["data_pas"].str.split(" ", expand=True)
    df = df.drop(columns=["data_pas", "hora"])
    df[["ano", "mês", "dia"]] = df["data"].str.split("-", expand=True)
    df = df.drop(columns=["data", "pais"])
    df = df.drop_duplicates()

    df.to_csv(novo_arquivo, index=False)

    return df

df = limpar_dados_incendio("focos_br_ref_2024.csv", "2024_limpo.csv")
display(df)

,lat,lon,estado,municipio,bioma,ano,mês,dia
0,-15.89572,-38.89957,BAHIA,BELMONTE,Mata Atlântica,2024,01,02
1,-7.49188,-38.88316,CEARÁ,BREJO SANTO,Caatinga,2024,01,02
2,-6.50564,-39.44122,CEARÁ,CARIÚS,Caatinga,2024,01,02
3,-6.50409,-39.43422,CEARÁ,CARIÚS,Caatinga,2024,01,02
4,-5.74166,-39.59352,CEARÁ,MOMBAÇA,Caatinga,2024,01,02
...,...,...,...,...,...,...,...,...
278294,-11.95043,-49.48899,TOCANTINS,FORMOSO DO ARAGUAIA,Cerrado,2024,12,31
278295,-18.83764,-50.07574,MINAS GERAIS,SANTA VITÓRIA,Cerrado,2024,12,31
278296,-21.91783,-47.15528,SÃO PAULO,CASA BRANCA,Cerrado,2024,12,31
278297,-23.73668,-52.86879,PARANÁ,TAPEJARA,Mata Atlântica,2024,12,31
278298,-18.79676,-54.88804,MATO GROSSO DO SUL,RIO VERDE DE MATO GROSSO,Cerrado,2024,12,31

Caso seja usado o google colab:

In [18]:
#from google.colab import drive
#drive.mount('/content/drive')

Concatenção dos arquivos:

In [21]:
#pasta onde os arquivos estão localizados
pasta = "."

#nome do arquivo csv final com os dados processados
arquivo_out = "casos_incendio.csv"

dataframes = []

#os.listdir para listar arquivos dentro da pasta
for arquivo in os.listdir(pasta):
    if arquivo.endswith("_limpo.csv"):
        caminho_arquivo = os.path.join(pasta,arquivo)
        df = pd.read_csv(caminho_arquivo)
        dataframes.append(df)
        
#para combinar os dataframes em um só
dados = pd.concat(dataframes, ignore_index=True)
dados = dados.sort_values(by=["ano","mês"], ascending=[False, True])
dados = dados.drop_duplicates()
dados.to_csv(arquivo_out, index=False)
dados

,lat,lon,estado,municipio,bioma,ano,mês,dia
1912436,-15.89572,-38.89957,BAHIA,BELMONTE,Mata Atlântica,2024,1,2
1912437,-7.49188,-38.88316,CEARÁ,BREJO SANTO,Caatinga,2024,1,2
1912438,-6.50564,-39.44122,CEARÁ,CARIÚS,Caatinga,2024,1,2
1912439,-6.50409,-39.43422,CEARÁ,CARIÚS,Caatinga,2024,1,2
1912440,-5.74166,-39.59352,CEARÁ,MOMBAÇA,Caatinga,2024,1,2
...,...,...,...,...,...,...,...,...
175700,-2.34100,-46.17800,MARANHÃO,CENTRO DO GUILHERME,Amazônia,2014,12,17
175701,-2.43100,-46.90600,PARÁ,PARAGOMINAS,Amazônia,2014,12,16
175704,-1.90500,-54.01300,PARÁ,MONTE ALEGRE,Amazônia,2014,12,30
175711,-1.91500,-48.13200,PARÁ,ACARÁ,Amazônia,2014,12,20
175712,-0.88600,-47.75300,PARÁ,MARAPANIM,Amazônia,2014,12,20

Para verificar as colunas:

In [23]:
pesquisar = dados[dados['ano']==2022]
pesquisar

,lat,lon,estado,municipio,bioma,ano,mês,dia
1501100,-7.06400,-39.16000,CEARÁ,CARIRIAÇU,Caatinga,2021,1,2
1501101,-6.14200,-36.25700,RIO GRANDE DO NORTE,SÃO TOMÉ,Caatinga,2021,1,2
1501102,-7.71700,-39.43300,PERNAMBUCO,SERRITA,Caatinga,2021,1,2
1501103,-13.15300,-45.51600,BAHIA,SÃO DESIDÉRIO,Cerrado,2021,1,2
1501104,-5.24000,-40.99100,PIAUÍ,BURITI DOS MONTES,Caatinga,2021,1,2
...,...,...,...,...,...,...,...,...
1457929,-24.46079,-48.51469,SÃO PAULO,IPORANGA,Mata Atlântica,2021,12,21
1459093,-20.20759,-57.71408,MATO GROSSO DO SUL,CORUMBÁ,Pantanal,2021,12,20
1459094,-20.20916,-57.72425,MATO GROSSO DO SUL,CORUMBÁ,Pantanal,2021,12,20
1459095,-20.45618,-57.82446,MATO GROSSO DO SUL,CORUMBÁ,Pantanal,2021,12,20
1459096,-22.33205,-54.83588,MATO GROSSO DO SUL,DOURADOS,Cerrado,2021,12,20